SnowflakePowered/librashader

- README.md
- librashader-reflect/src/error.rs
- librashader-reflect/src/lib.rs
- librashader-reflect/src/reflect/cross.rs
- librashader-reflect/src/reflect/semantics.rs
- librashader-runtime-d3d11/src/lib.rs
- librashader-runtime-gl/src/binding.rs
- librashader-runtime-gl/src/filter_chain/filter_impl.rs
- librashader-runtime-gl/src/filter_pass.rs
- librashader-runtime-gl/src/lib.rs
- librashader-runtime/src/binding.rs
- librashader-runtime/src/uniforms.rs
Some shaders do really funky shit and bind the same variable name to the UBO and PCB accessed in different stages. This allows for a uniform to be bound to both the UBO and PCB to fix these edge cases.
> Allow binding uniform names to both UBO and Push Constants

- README.md
- librashader-capi/build.rs
Will ensure D3D12 DLL dependencies are not loaded for non-D3D12 environments
> capi: emit delayload link arg for D3D12 dependencies

- librashader-runtime-d3d11/src/samplers.rs
- librashader-runtime-d3d12/src/samplers.rs
Regression from 8ed244f6faee3ccd5520269033f5a17bd5c0c467
> d3d11/12: fix sampler set creation

- .github/workflows/build.yml
- Cargo.lock
- Cargo.toml
- librashader-cache/src/compilation.rs
- librashader-cache/src/d3d.rs
- librashader-capi/src/error.rs
- librashader-preprocess/src/include.rs
- librashader-presets/src/lib.rs
- librashader-presets/src/parse/preset.rs
- librashader-presets/src/parse/value.rs
- librashader-reflect/Cargo.toml
- librashader-reflect/src/back/dxil.rs
- librashader-reflect/src/reflect/cross.rs
- librashader-reflect/src/reflect/semantics.rs
- librashader-runtime-d3d11/src/filter_chain.rs
- librashader-runtime-d3d12/src/filter_chain.rs
- librashader-runtime-d3d12/src/luts.rs
- librashader-runtime-d3d12/src/util.rs
- librashader-runtime-d3d12/tests/hello_triangle/mod.rs
- librashader-runtime-d3d12/tests/triangle.rs
- librashader-runtime-gl/src/filter_chain/filter_impl.rs
- librashader-runtime-gl/src/lib.rs
- librashader-runtime-vk/src/filter_chain.rs
- librashader-runtime-vk/src/memory.rs
* Fix `drain_filter` feature name to `extract_if`
* fix TAIT registration changes
* update spirv-to-dxil
* cargo fmt
> nightly maintenance for rustc 1.73

- .github/workflows/build-linux-arm64.yml
- .github/workflows/build.yml
- Cargo.lock
- README.md
- librashader-build-script/src/main.rs
- librashader-cache/Cargo.toml
- librashader-cache/src/compilation.rs
- librashader-reflect/Cargo.toml
- librashader-reflect/src/back/mod.rs
- librashader-reflect/src/error.rs
- librashader/src/lib.rs
* only build dxil on windows
* cross-compile arm64 linux
> build: update spirv-to-dxil-sys to reduce mesa build reqs

- Cargo.lock
- librashader-presets/Cargo.toml
- librashader-presets/src/extract_if.rs
- librashader-presets/src/lib.rs
- librashader-presets/src/parse/preset.rs
- librashader-presets/src/parse/value.rs
- librashader-runtime-d3d12/src/descriptor_heap.rs
- librashader-runtime-d3d12/src/lib.rs
- librashader-runtime-gl/Cargo.toml
- librashader-runtime-gl/src/gl/gl3/draw_quad.rs
- librashader-runtime-gl/src/lib.rs
- librashader-runtime-vk/tests/triangle.rs
- librashader-runtime/src/array_chunks_mut.rs
- librashader-runtime/src/image.rs
- librashader-runtime/src/lib.rs
Reduces the list of unstable features to 
```
#![feature(try_blocks)]
#![feature(pointer_is_aligned)]
#![feature(vec_into_raw_parts)]
#![feature(let_chains)]
#![feature(type_alias_impl_trait)]
#![feature(impl_trait_in_assoc_type)]
```
This will probably remain as a draft because it's not too useful to just get rid of some unstable features, especially when librashader_capi still needs `pointer_is_aligned` and `vec_into_raw_parts`, which can't be effectively polyfilled.
> Make things 'closer' to building on stable

- .github/workflows/package-obs.yml
- .github/workflows/publish-obs.yml
- Cargo.lock
- README.md
- librashader-reflect/Cargo.toml
- librashader.copr.spec
- pkg/librashader.pc
- pkg/librashader.spec
- pkg/obs/PKGBUILD
- pkg/obs/_service
- pkg/obs/librashader.spec
Add support for building librashader as Linux packages on exotic architectures via OpenBuildService.
Unfortunately, since Debian Bookwork is stuck on rustc 1.63, we can only support Debian Trixie and above bases.
These packages set `SONAME` in accordance with the ABI version on build.
Fixes #26
> Package shared library on Linux

- .github/workflows/build.yml
- include/librashader_ld.h
- librashader-build-script/src/main.rs
This allows building librashader on macOS and other UNIX targets such as FreeBSD
Note that despite compiling for macOS, the OpenGL drivers on macOS do not seem to be compatible with the slangp shaders; even upstream retroarch only allows glsl shaders on macOS unless using metal. 
It may be possible to utilise MoltenVK to use vulkan on macOS, which may be a decent middle ground; but my target project  (ares) currently lacks both vulkan and metal driver backends, meaning this is as far as we can get for now.
Even so, this is a step in the right direction and at least allows librashader to load and (attempt) to compile shaders.
> support building for macOS and non-linux unixes

- Cargo.lock
- librashader-reflect/src/reflect/cross/glsl.rs
- librashader-reflect/src/reflect/cross/msl.rs
- librashader-reflect/src/reflect/naga/msl.rs
- librashader-runtime-gl/Cargo.toml
- librashader-runtime-gl/src/gl/gl3/draw_quad.rs
- librashader-runtime-gl/src/gl/gl46/draw_quad.rs
- librashader-runtime-gl/src/gl/mod.rs
- librashader-runtime-gl/tests/hello_triangle/gl3.rs
- librashader-runtime-gl/tests/triangle.rs
- librashader-runtime-vk/Cargo.toml
- librashader-runtime-vk/src/draw_quad.rs
- librashader-runtime-wgpu/src/draw_quad.rs
* don't unset vertex inputs attribs when compiling glsl
* use structs for quad data rather than [f32;16]
> opengl + other runtime fixes

- librashader-runtime-vk/src/draw_quad.rs
- librashader-runtime-vk/src/filter_chain.rs
- librashader-runtime-vk/src/filter_pass.rs
- librashader-runtime-vk/src/framebuffer.rs
Anything that isn't `Drop` doesn't need to hold on to a `device`.
> vk: remove unneeded device arcs

- Cargo.lock
- Cargo.toml
- librashader-cache/Cargo.toml
- librashader-capi/Cargo.toml
- librashader-common/Cargo.toml
- librashader-runtime-d3d11/Cargo.toml
- librashader-runtime-d3d11/src/draw_quad.rs
- librashader-runtime-d3d11/src/filter_chain.rs
- librashader-runtime-d3d11/src/framebuffer.rs
- librashader-runtime-d3d11/src/graphics_pipeline.rs
- librashader-runtime-d3d11/src/texture.rs
- librashader-runtime-d3d11/tests/hello_triangle/mod.rs
- librashader-runtime-d3d11/tests/hello_triangle/texture.rs
- librashader-runtime-d3d12/Cargo.toml
- librashader-runtime-d3d12/src/filter_chain.rs
- librashader-runtime-d3d12/src/framebuffer.rs
- librashader-runtime-d3d12/tests/hello_triangle/mod.rs
- librashader-runtime/Cargo.toml
- librashader/Cargo.toml
No real huge differences here. 0.52.0 seems to be pretty widely used at the moment, whereas 0.53.0 is too fresh.
> deps: upgrade to windows 0.52

- Cargo.lock
- librashader-runtime-d3d12/Cargo.toml
- librashader-runtime-d3d12/src/descriptor_heap.rs
- librashader-runtime-d3d12/tests/hello_triangle/descriptor_heap.rs
- librashader-runtime-vk/src/draw_quad.rs
- librashader-runtime-vk/src/filter_chain.rs
- librashader-runtime-vk/src/memory.rs
- librashader-runtime-vk/src/texture.rs
- librashader-runtime-vk/src/util.rs
- librashader-runtime-vk/tests/hello_triangle/memory.rs
- librashader-runtime-vk/tests/hello_triangle/mod.rs
- librashader-runtime-vk/tests/hello_triangle/util.rs
- librashader-runtime-vk/tests/hello_triangle/vulkan_base.rs
* use a `Mutex` to guard vulkan allocator lock rather than `RwLock` because we have no readers.
* use atomics for d3d12 `DescriptorHeap`
> lock improvements

- librashader-cache/src/cache.rs
- librashader-runtime-gl/src/filter_chain/filter_impl.rs
- librashader-runtime-gl/src/gl/framebuffer.rs
- librashader-runtime-gl/src/gl/gl3/framebuffer.rs
- librashader-runtime-gl/src/gl/gl3/lut_load.rs
- librashader-runtime-gl/src/gl/gl46/framebuffer.rs
- librashader-runtime-gl/src/gl/gl46/lut_load.rs
- librashader-runtime-gl/src/gl/mod.rs
- librashader-runtime-gl/tests/triangle.rs
Fixes issues with LUT sampling on crt-hyllian.
See https://github.com/libretro/slang-shaders/issues/552
> gl: load luts with TopLeft orientation, flipping render buffer instead

- include/librashader.h
- librashader-capi/cbindgen.toml
Includes with backslash won't work on Linux/BSD.
> capi: fix malformed vulkan include

- librashader-presets/src/error.rs
useful to have when debugging preset errors
> presets: show file name and details on io error

- librashader-capi/src/runtime/d3d11/filter_chain.rs
- librashader-capi/src/runtime/d3d12/filter_chain.rs
- librashader-runtime-d3d11/src/filter_chain.rs
- librashader-runtime-d3d11/src/filter_pass.rs
- librashader-runtime-d3d11/src/framebuffer.rs
- librashader-runtime-d3d11/src/lib.rs
- librashader-runtime-d3d11/src/luts.rs
- librashader-runtime-d3d11/src/texture.rs
- librashader-runtime-d3d11/src/util.rs
- librashader-runtime-d3d11/tests/hello_triangle/mod.rs
- librashader-runtime-d3d11/tests/triangle.rs
- librashader-runtime-d3d12/src/texture.rs
- librashader-runtime-d3d12/src/util.rs
- librashader-runtime-d3d12/tests/hello_triangle/mod.rs
- librashader-runtime-d3d12/tests/triangle.rs
- librashader/src/lib.rs
Rely on `GetDesc` where possible.
~~Unsure if I want to move forward with this though, it is an ABI breaking change for not that much gain. If we eventually don't care about breaking ABI like for #66, we could roll these changes with ABI version `2`.~~
This actually doesn't break ABI, unless we want to get rid of some dummy fields..
> Rely on `GetDesc` rather than manual size data

- librashader-reflect/src/front/glslang.rs
- librashader-reflect/src/front/spirv_passes/link_input_outputs.rs
Improve vert/frag linkage to reassign unused vertex outputs to the end. 
This lets spirv-to-dxil/spirv-to-dxbc better handle reordering (i.e., make it completely unnecessary), or at least keep the expected order of inouts for user code.
> reflect: improve inout link algorithm

- librashader-reflect/src/front/glslang.rs
- librashader-reflect/src/front/spirv_passes/link_input_outputs.rs
Reverts SnowflakePowered/librashader#97
This breaks `bezel/koko-aio/Presets-ng/Monitor-Balanced.slangp`
```
Assertion failed: nir_shader_can_read_output(&b.shader->info), file native/mesa/src/compiler/nir\nir_lower_io_to_vector.c, line 478
```
> Revert "reflect: improve inout link algorithm"

- Cargo.lock
- librashader-runtime-d3d12/Cargo.toml
- librashader-runtime-d3d12/src/buffer.rs
- librashader-runtime-d3d12/src/draw_quad.rs
- librashader-runtime-d3d12/src/error.rs
- librashader-runtime-d3d12/src/filter_chain.rs
- librashader-runtime-d3d12/src/framebuffer.rs
- librashader-runtime-d3d12/src/luts.rs
- librashader-runtime-d3d12/tests/triangle.rs
- librashader-runtime-vk/src/filter_chain.rs
- librashader-runtime-vk/src/memory.rs
- librashader-runtime-vk/src/util.rs
* Use `ManuallyDrop` for Vulkan buffer rather than Option
* Use `gpu_allocator` to suballocate buffers rather than `CreateCommittedResource`
> Vulkan and D3D12 memory improvements

- librashader-capi/src/error.rs
- librashader-capi/src/ffi.rs
- librashader-capi/src/lib.rs
- librashader-capi/src/runtime/d3d11/filter_chain.rs
- librashader-capi/src/runtime/d3d12/filter_chain.rs
- librashader-capi/src/runtime/d3d9/filter_chain.rs
- librashader-capi/src/runtime/gl/filter_chain.rs
- librashader-capi/src/runtime/mtl/filter_chain.rs
- librashader-capi/src/runtime/vk/filter_chain.rs
Uses an IIFE + return type changes to remove the need for try blocks
Allows us to remove another nightly feature needed
> capi: remove dependency on `try_blocks`

- librashader-runtime-d3d11/src/filter_chain.rs
- librashader-runtime-d3d11/tests/triangle.rs
- librashader-runtime-d3d12/src/filter_chain.rs
- librashader-runtime-d3d9/src/filter_chain.rs
- librashader-runtime-gl/src/filter_chain/filter_impl.rs
- librashader-runtime-mtl/src/filter_chain.rs
- librashader-runtime-vk/src/filter_chain.rs
- librashader-runtime-wgpu/src/filter_chain.rs
- librashader-runtime/src/binding.rs
- librashader-runtime/src/framebuffer.rs
#117 fixes the problem of PassFeedback0 being unwritten if it is last frame. However many shaders don't need to use PassFeedback at all, and drawing twice is not zero-cost unlike feedback for other frames which is just a mem swap.
This does some reflection to determine if the last feedback pass is ever read, and only to draw to the output_texture framebuffer if needed. This allows the final pass to be zero-cost again unless it's needed to be read.
Further optimizations could be applied narrowly to the case by adding an implicit blit pass so the final pass is only drawn once.
> Don't draw PassFeedbackN if N is the final pass and not read.

- librashader-preprocess/src/lib.rs
- librashader-preprocess/src/pragma.rs
- librashader-reflect/src/reflect/presets.rs
- librashader-reflect/src/reflect/semantics.rs
* Fix handling of `#pragma name`
* Fix `CurrentSubFrame` being parsed as `TotalSubFrames`, this would cause issues for shaders with UBOs that used both.
> Preset and reflect fixes

- include/librashader_ld.h
- librashader-capi/src/error.rs
These are the only typos I've noticed while working on a Metal implementation.
> capi: Fix Metal error message, function header

- librashader-capi/src/runtime/d3d9/filter_chain.rs
- librashader-runtime-d3d9/src/draw_quad.rs
- librashader-runtime-d3d9/src/filter_chain.rs
- librashader-runtime-d3d9/src/luts.rs
- librashader-runtime-d3d9/tests/hello_triangle/mod.rs
- librashader-runtime-gl/src/error.rs
- librashader-runtime-gl/src/filter_chain/chain.rs
- librashader-runtime-gl/src/filter_pass.rs
- librashader-runtime-gl/src/gl/framebuffer.rs
- librashader-runtime-gl/src/gl/gl3/framebuffer.rs
- librashader-runtime-gl/src/gl/gl46/framebuffer.rs
- librashader-runtime-gl/src/gl/mod.rs
- librashader-runtime-gl/tests/hello_triangle/gl3.rs
- librashader-runtime-gl/tests/hello_triangle/gl46.rs
- librashader-runtime-gl/tests/triangle.rs
Add some small bugfixes to work around edge cases exposed by #109 
* gl: always ensure framebuffers are bound
* d3d9: disable alpha blending
* d3d9: load LUTS as BGRA8 instead of ARGB8
* d3d9: accept input image by ref to avoid clone
> Bugfixes and improvements from testing harness experimentation

- CLI.md
- README.md
- librashader-capi/src/ctypes.rs
- librashader-cli/src/cli/main.rs
- librashader-cli/src/render/d3d11.rs
- librashader-cli/src/render/d3d12/mod.rs
- librashader-cli/src/render/d3d9.rs
- librashader-cli/src/render/gl/mod.rs
- librashader-cli/src/render/mod.rs
- librashader-cli/src/render/mtl.rs
- librashader-cli/src/render/vk/mod.rs
- librashader-cli/src/render/wgpu.rs
currently broken in d3d11 and d3d12 for unknown reasons (possibly mtl too)
> cli(render): allow specifying output dimensions

- librashader-runtime/src/binding.rs
- librashader-runtime/src/framebuffer.rs
Previously, if a shader used `OriginalHistory1` and no further history, we would not create enough space in the history queue.
Fixes https://github.com/raphamorim/rio/issues/788
> fix: create a history queue if required_images is 1

- Cargo.lock
- Cargo.toml
- librashader-capi/Cargo.toml
- librashader-cli/Cargo.toml
- librashader-cli/src/render/gl/mod.rs
- librashader-cli/src/render/mtl.rs
- librashader-cli/src/render/wgpu.rs
- librashader-common/Cargo.toml
- librashader-reflect/Cargo.toml
- librashader-runtime-gl/src/gl/gl3/lut_load.rs
- librashader-runtime-gl/src/gl/gl46/lut_load.rs
- librashader-runtime-mtl/Cargo.toml
- librashader-runtime-mtl/src/buffer.rs
- librashader-runtime-mtl/src/draw_quad.rs
- librashader-runtime-mtl/src/filter_chain.rs
- librashader-runtime-mtl/tests/hello_triangle/main.rs
- librashader-runtime-wgpu/src/error.rs
- librashader-runtime-wgpu/src/filter_chain.rs
- librashader/Cargo.toml
* wgpu 25
* objc2 0.3
* glow 0.16
> dependency updayes
